name: Issue PR Labeler

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - reopened

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: read # required to read configuration yml file
      issues: write # required to add labels to issues
      pull-requests: write # required to add labels to pull requests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print GitHub Context
        run: |
          echo "Context: ${{ toJson(github) }}"

      - name: Print Environment Variables
        run: env

      - name: Run Issue PR Labeler
        uses: hoho4190/issue-pr-labeler@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # disable-bot: true
          # config-file-name: .github/labeler-config.yml
